---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.20.0
  name: oscmachines.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: OscMachine
    listKind: OscMachineList
    plural: oscmachines
    singular: oscmachine
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.node.vm.vmType
      name: VM Type
      type: string
    - jsonPath: .spec.providerID
      name: ProviderID
      type: string
    - jsonPath: .status.vmState
      name: State
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: OscMachine is the Schema for the oscmachines API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: OscMachineSpec defines the desired state of OscMachine
            properties:
              node:
                properties:
                  clusterName:
                    description: unused
                    type: string
                  image:
                    properties:
                      accountId:
                        description: The image account owner ID.
                        type: string
                      name:
                        description: The image name.
                        type: string
                      outscaleOpenSource:
                        description: Use an "Outscale Opensource" image
                        type: boolean
                      resourceId:
                        description: unused
                        type: string
                    type: object
                  keypair:
                    description: deprecated, use vm.keypairName
                    properties:
                      clusterName:
                        description: Deprecated
                        type: string
                      deleteKeypair:
                        description: Deprecated
                        type: boolean
                      name:
                        description: Deprecated
                        type: string
                      publicKey:
                        description: Deprecated
                        type: string
                      resourceId:
                        description: Deprecated
                        type: string
                    type: object
                  reconciliationRule:
                    description: 'Reconciliation rules (default: {*, onChange})'
                    properties:
                      appliesTo:
                        description: The list of items this rule applies to (bastion,
                          net, netPeering, netPeering/routes, subnet, internetService,
                          netAccessPoint, natService, routeTable, securityGroup, loadbalancer,
                          vm or * for all)
                        items:
                          enum:
                          - bastion
                          - net
                          - netPeering
                          - netPeering/routes
                          - subnet
                          - internetService
                          - netAccessPoint
                          - natService
                          - routeTable
                          - securityGroup
                          - loadbalancer
                          - vm
                          - '*'
                          type: string
                        type: array
                      mode:
                        description: 'The mode of reconciliation: onChange (only when
                          the spec change, default), always, random (onChange + randomPercent%
                          chance)'
                        enum:
                        - onChange
                        - always
                        - random
                        type: string
                      reconciliationChance:
                        description: The chance (in percent, 1-100) of a reconcilation
                          happening when no change have been detected (when mode=random)
                        type: integer
                    type: object
                  vm:
                    properties:
                      clusterName:
                        description: unused
                        type: string
                      deviceName:
                        description: unused
                        type: string
                      imageId:
                        type: string
                      keypairName:
                        description: The keypair name
                        type: string
                      loadBalancerName:
                        description: unused
                        type: string
                      name:
                        type: string
                      privateIps:
                        items:
                          properties:
                            name:
                              type: string
                            privateIp:
                              type: string
                          type: object
                        type: array
                      publicIp:
                        description: If set, a public IP will be configured.
                        type: boolean
                      publicIpName:
                        description: unused
                        type: string
                      publicIpPool:
                        description: The name of the pool from which public IPs will
                          be picked.
                        type: string
                      replica:
                        description: unused
                        format: int32
                        type: integer
                      resourceId:
                        description: The resource id of the vm (not set anymore)
                        type: string
                      role:
                        description: The node role (controlplane or worker, worker
                          by default).
                        type: string
                      rootDisk:
                        properties:
                          rootDiskIops:
                            description: The root disk iops (io1 volumes only) (1500
                              by default)
                            format: int32
                            type: integer
                          rootDiskSize:
                            description: The volume size in gibibytes (GiB) (60 by
                              default)
                            format: int32
                            type: integer
                          rootDiskType:
                            description: The volume type (io1, gp2 or standard) (io1
                              by default)
                            type: string
                        type: object
                      securityGroupNames:
                        description: The list of security groups to use (deprecated,
                          use controlplane and/or worker roles on security groups)
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      subnetName:
                        description: The subnet of the node (deprecated, use controlplane
                          and/or worker roles on subnets)
                        type: string
                      subregionName:
                        type: string
                      tags:
                        additionalProperties:
                          type: string
                        description: Tags to add to the VM.
                        type: object
                      vmType:
                        description: The type of vm (tinav6.c4r8p1 by default)
                        type: string
                      volumeDeviceName:
                        description: unused
                        type: string
                      volumeName:
                        description: unused
                        type: string
                    required:
                    - keypairName
                    type: object
                  volumes:
                    items:
                      properties:
                        device:
                          description: The volume device (/dev/xvdX)
                          type: string
                        fromSnapshot:
                          description: The id of a snapshot to use as a volume source.
                          type: string
                        iops:
                          description: The volume iops (io1 volumes only)
                          format: int32
                          type: integer
                        name:
                          description: The volume name.
                          type: string
                        resourceId:
                          description: (unused)
                          type: string
                        size:
                          description: The volume size in gibibytes (GiB)
                          format: int32
                          type: integer
                        subregionName:
                          description: (unused)
                          type: string
                        volumeType:
                          description: The volume type (io1, gp2 or standard)
                          type: string
                      required:
                      - device
                      type: object
                    type: array
                type: object
              providerID:
                type: string
            type: object
          status:
            description: OscMachineStatus defines the observed state of OscMachine
            properties:
              addresses:
                items:
                  description: NodeAddress contains information for the node's address.
                  properties:
                    address:
                      description: The node address.
                      type: string
                    type:
                      description: Node address type, one of Hostname, ExternalIP
                        or InternalIP.
                      type: string
                  required:
                  - address
                  - type
                  type: object
                type: array
              conditions:
                description: Conditions provide observations of the operational state
                  of a Cluster API resource.
                items:
                  description: Condition defines an observation of a Cluster API resource
                    operational state.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed. If that is not known, then using the time when
                        the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This field may be empty.
                      maxLength: 10240
                      minLength: 1
                      type: string
                    reason:
                      description: |-
                        reason is the reason for the condition's last transition in CamelCase.
                        The specific API may choose whether or not this field is considered a guaranteed API.
                        This field may be empty.
                      maxLength: 256
                      minLength: 1
                      type: string
                    severity:
                      description: |-
                        severity provides an explicit classification of Reason code, so the users or machines can immediately
                        understand the current situation and act accordingly.
                        The Severity field MUST be set only when Status=False.
                      maxLength: 32
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: |-
                        type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources like Available, but because arbitrary conditions
                        can be useful (see .node.status.conditions), the ability to deconflict is important.
                      maxLength: 256
                      minLength: 1
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              failureDomain:
                type: string
              failureMessage:
                type: string
              failureReason:
                description: MachineStatusError defines errors states for Machine
                  objects.
                type: string
              node:
                description: deprecated, replaced by resources
                properties:
                  imageRef:
                    description: Image references (not set anymore)
                    properties:
                      resourceMap:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  keypairRef:
                    description: Keypair references (not set anymore)
                    properties:
                      resourceMap:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  linkPublicIpRef:
                    description: LinkPublicIp references (not set anymore)
                    properties:
                      resourceMap:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  publicIpIdRef:
                    description: PublicIp references (not set anymore)
                    properties:
                      resourceMap:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  vmRef:
                    description: Vm references (not set anymore)
                    properties:
                      resourceMap:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  volumeRef:
                    description: Volume references (not set anymore)
                    properties:
                      resourceMap:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                type: object
              ready:
                type: boolean
              reconcilerGeneration:
                additionalProperties:
                  format: int64
                  type: integer
                type: object
              resources:
                properties:
                  image:
                    additionalProperties:
                      type: string
                    type: object
                  publicIps:
                    additionalProperties:
                      type: string
                    type: object
                  vm:
                    additionalProperties:
                      type: string
                    type: object
                  volumes:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              vmState:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
